CREATE FUNCTION IF NOT EXISTS GET_SET_ITEM(str VARCHAR(255), delim VARCHAR(12), pos INT)
RETURNS VARCHAR(255)
RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(str,delim,pos),CHAR_LENGTH(SUBSTRING_INDEX(str,delim,pos-1)) + 1),delim,'');	